version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "✅ This is the updated buildspec.yaml being used"
      - echo Installing Maven...
      - yum install -y maven

  pre_build:
    commands:
      - echo Starting pre-build phase...
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - export REPOSITORY_URI=448214416344.dkr.ecr.eu-west-2.amazonaws.com/springboot-course-service-repo
      - aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo "Setting IMAGE_TAG..."
      - export IMAGE_TAG=build-${CODEBUILD_BUILD_ID##*:}
      - echo IMAGE_TAG=$IMAGE_TAG

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - export DOCKER_CONTAINER_NAME=springboot-course-service-repo
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Printing imagedefinitions.json:
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/course-service.jar
